# @package _global_
model:
  # _target_: models.touch_detect.TouchDetectionModel
  _target_: models.simple_cnn.SimpleCNNModel
  pre_trained: False
  n_classes: 2
data:
  _target_: datamodules.touch_detect.TouchDetectDataModule
  path: "/home/samyim/Dataset/modify/left-bottlecap-gray/"
  exclude: []
  transform:
    # scales: [ 240, 320 ]
    scales: [ 64, 64 ]    
    mean: [ 0,0,0 ]
    std: [ 1,1,1 ]
#    mean: [0.39534545 ,0.41399255 ,0.40639707]
#    std: [0.1094584  ,0.10767335 ,0.17195037]

optimizer:
  type: "SGD"
#  lr: 0.00847
  lr: 0.00847
  lr_patience: 5
  weight_decay: 1.0115995395401329e-08
training:
  seed: 42
  batch_size: 64
  n_threads: 10
  gpu_ids: 1
  n_epochs: 50
  train_val_ratio: 0.7
  pin_memory: 1
checkpoints:
  path: "./checkpoints/"
  last_epoch: "last_epoch.chkpt"
  temp_epoch: "last_epoch.chkpt.tmp"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 5
  restore_best: 1
  csv_file_name: "training_log.csv"
  save_weights_only: True
general:
  verbose: True
  tb_log_path: "./tb_logs/"

